# Generated by Django 4.0.4 on 2022-04-29 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courier', '0002_courier_created_courier_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.IntegerField()),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_salaries', to='courier.courier')),
            ],
        ),
    ]
