# Generated by Django 4.0.4 on 2022-04-29 12:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeaddition',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeaddition',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomeaddition',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 29)),
        ),
        migrations.AddField(
            model_name='incomeaddition',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incomeaddition',
            name='time',
            field=models.TimeField(default=datetime.time(12, 49, 11, 754373)),
        ),
        migrations.AddField(
            model_name='incomededuction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomededuction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incomededuction',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 29)),
        ),
        migrations.AddField(
            model_name='incomededuction',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='incomededuction',
            name='time',
            field=models.TimeField(default=datetime.time(12, 49, 11, 754373)),
        ),
        migrations.AddField(
            model_name='tripincome',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripincome',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tripincome',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 29)),
        ),
        migrations.AddField(
            model_name='tripincome',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tripincome',
            name='time',
            field=models.TimeField(default=datetime.time(12, 49, 11, 754373)),
        ),
    ]
