# Generated by Django 4.0.4 on 2022-04-29 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_incomeaddition_amount_incomeaddition_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeaddition',
            name='time',
            field=models.TimeField(default=datetime.time(12, 50, 59, 238369)),
        ),
        migrations.AlterField(
            model_name='incomededuction',
            name='time',
            field=models.TimeField(default=datetime.time(12, 50, 59, 238369)),
        ),
        migrations.AlterField(
            model_name='tripincome',
            name='time',
            field=models.TimeField(default=datetime.time(12, 50, 59, 238369)),
        ),
    ]
