# Generated by Django 4.0.4 on 2022-04-29 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_alter_incomeaddition_time_alter_incomededuction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeaddition',
            name='time',
            field=models.TimeField(default=datetime.time(17, 29, 50, 368240)),
        ),
        migrations.AlterField(
            model_name='incomededuction',
            name='time',
            field=models.TimeField(default=datetime.time(17, 29, 50, 368240)),
        ),
        migrations.AlterField(
            model_name='tripincome',
            name='time',
            field=models.TimeField(default=datetime.time(17, 29, 50, 368240)),
        ),
    ]
