# Generated by Django 4.0.4 on 2022-04-29 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_incomeaddition_time_alter_incomededuction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomeaddition',
            name='time',
            field=models.TimeField(default=datetime.time(18, 0, 10, 280137)),
        ),
        migrations.AlterField(
            model_name='incomededuction',
            name='time',
            field=models.TimeField(default=datetime.time(18, 0, 10, 280137)),
        ),
        migrations.AlterField(
            model_name='tripincome',
            name='time',
            field=models.TimeField(default=datetime.time(18, 0, 10, 280137)),
        ),
    ]
